assetic:
    assets:
        css:
            inputs:
                - 'vendor/Bootstrap/css/bootstrap.min.css'
                - 'vendor/Animate/animate.min.css'
                - 'vendor/font-awesome/css/font-awesome.min.css'
                - 'stylesheets/spinner.css'
                - 'stylesheets/desktop.css'
                - 'bower_components/angular-loading-bar/build/loading-bar.min.css'
                - 'bower_components/fileicon.css/fileicon.css'
                - 'stylesheets/extensions.css'

        vendors:
            inputs:
                - 'vendor/yepnope/yepnope-2.0.0.js'
                - 'vendor/jQuery/jquery-2.1.4.min.js'
                - 'bower_components/snabbt.js/snabbt.min.js'
                - 'vendor/Moment/moment.min.js'
                - 'vendor/Wow/wow.min.js'
                - 'vendor/Bootstrap/js/bootstrap.min.js'
                - 'bower_components/angular-full/angular.min.js'
                - 'bower_components/angular-full/angular-animate.min.js'
                - 'bower_components/angular-full/angular-sanitize.min.js'
                - 'vendor/ui-router/angular-ui-router.min.js'
                - 'vendor/Angular/angular-touch.min.js'
                - 'vendor/angular-translate/angular-translate.js'
                - 'vendor/angular-translate/angular-translate-loader-static-files.js'
                - 'bower_components/videogular/videogular.min.js'
                - 'bower_components/videogular-buffering/vg-buffering.min.js'
                - 'bower_components/videogular-controls/vg-controls.min.js'
                - 'bower_components/videogular-overlay-play/vg-overlay-play.min.js'
                - 'bower_components/videogular-poster/vg-poster.min.js'
                - 'bower_components/angular-loading-bar/build/loading-bar.min.js'
        modules:
            inputs:
                - 'compiled/Kernel.js'
        models:
            inputs:
                - 'javascripts/Model/*'
        services:
            inputs:
                - 'javascripts/Services/*'
        controllers:
            inputs:
                - 'javascripts/Controller/*'
        components:
            inputs:
                - 'javascripts/Components/*'