# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ JDareClankBundle, riki34FrontendBundle, riki34BackendBundle ]
    filters:
        cssrewrite: ~