<?php

namespace riki34\BackendBundle\Repository;

/**
 * ExtensionApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtensionApplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
