<?php

namespace riki34\BackendBundle\Repository;

/**
 * UserFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFileRepository extends \Doctrine\ORM\EntityRepository
{

}
